// ─── 5 Design Styles ───
// Replace 200+ templates with 5 curated visual styles.
// Each style ONLY changes colors/fonts/spacing — NOT layout.

import type { DesignStyle } from "./types";

export const STYLES: DesignStyle[] = [
  // ─── 1. Corporate — Navy & Gold authority ───
  {
    id: "corporate",
    name: "Corporate",
    colors: {
      accent: "#1e3a5f",
      accentLight: "#eef2f7",
      headerBg: "#1e3a5f",
      headerText: "#ffffff",
      sidebarBg: "#f5f7fa",
      sidebarText: "#1e3a5f",
      bodyText: "#1f2937",
      mutedText: "#6b7280",
      border: "#e2e8f0",
    },
    font: "sans",
    headingStyle: "underline",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "text",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
  // ─── 2. Minimal — Clean monochrome elegance ───
  {
    id: "minimal",
    name: "Minimal",
    colors: {
      accent: "#374151",
      accentLight: "#f3f4f6",
      headerBg: "#ffffff",
      headerText: "#111827",
      sidebarBg: "#f9fafb",
      sidebarText: "#374151",
      bodyText: "#1f2937",
      mutedText: "#9ca3af",
      border: "#e5e7eb",
    },
    font: "sans",
    headingStyle: "minimal",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "text",
    experienceStyle: "compact",
    sectionDivider: "none",
  },
  // ─── 3. Executive — Deep emerald prestige ───
  {
    id: "executive",
    name: "Executive",
    colors: {
      accent: "#15503b",
      accentLight: "#ecfdf5",
      headerBg: "#15503b",
      headerText: "#ffffff",
      sidebarBg: "#f0faf6",
      sidebarText: "#15503b",
      bodyText: "#1c1917",
      mutedText: "#6b7280",
      border: "#d1e7dd",
    },
    font: "serif",
    headingStyle: "uppercase-bar",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "dots",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
  // ─── 4. Creative — Bold violet energy ───
  {
    id: "creative",
    name: "Creative",
    colors: {
      accent: "#6d28d9",
      accentLight: "#f3f0ff",
      headerBg: "#6d28d9",
      headerText: "#ffffff",
      sidebarBg: "#faf8ff",
      sidebarText: "#4c1d95",
      bodyText: "#1f2937",
      mutedText: "#6b7280",
      border: "#e0d6fe",
    },
    font: "sans",
    headingStyle: "pill",
    density: "compact",
    borderRadius: "6px",
    showIcons: true,
    skillDisplay: "tags",
    experienceStyle: "card",
    sectionDivider: "gradient",
  },
  // ─── 5. Modern — Teal sophistication ───
  {
    id: "modern",
    name: "Modern",
    colors: {
      accent: "#0d7377",
      accentLight: "#edfafa",
      headerBg: "#0d7377",
      headerText: "#f0fdfa",
      sidebarBg: "#f0faf9",
      sidebarText: "#134e4a",
      bodyText: "#1f2937",
      mutedText: "#64748b",
      border: "#cceceb",
    },
    font: "sans",
    headingStyle: "bordered",
    density: "compact",
    borderRadius: "4px",
    showIcons: true,
    skillDisplay: "bars",
    experienceStyle: "timeline",
    sectionDivider: "none",
  },
  // ─── 6. Charcoal — Dark slate authority ───
  {
    id: "charcoal",
    name: "Charcoal",
    colors: {
      accent: "#334155",
      accentLight: "#f1f5f9",
      headerBg: "#1e293b",
      headerText: "#f8fafc",
      sidebarBg: "#f8fafc",
      sidebarText: "#334155",
      bodyText: "#1e293b",
      mutedText: "#64748b",
      border: "#e2e8f0",
    },
    font: "sans",
    headingStyle: "filled",
    density: "compact",
    borderRadius: "2px",
    showIcons: false,
    skillDisplay: "tags",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
  // ─── 7. Burgundy — Classic wine prestige ───
  {
    id: "burgundy",
    name: "Burgundy",
    colors: {
      accent: "#7f1d1d",
      accentLight: "#fef2f2",
      headerBg: "#7f1d1d",
      headerText: "#ffffff",
      sidebarBg: "#fdf6f6",
      sidebarText: "#7f1d1d",
      bodyText: "#1c1917",
      mutedText: "#78716c",
      border: "#e7d5d5",
    },
    font: "serif",
    headingStyle: "underline",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "dots",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
  // ─── 8. Azure — Bright blue clarity ───
  {
    id: "azure",
    name: "Azure",
    colors: {
      accent: "#1d4ed8",
      accentLight: "#eff6ff",
      headerBg: "#1d4ed8",
      headerText: "#ffffff",
      sidebarBg: "#f0f5ff",
      sidebarText: "#1e3a8a",
      bodyText: "#1f2937",
      mutedText: "#6b7280",
      border: "#dbeafe",
    },
    font: "sans",
    headingStyle: "bordered",
    density: "compact",
    borderRadius: "4px",
    showIcons: true,
    skillDisplay: "bars",
    experienceStyle: "timeline",
    sectionDivider: "none",
  },
  // ─── 9. Slate — Cool professional calm ───
  {
    id: "slate",
    name: "Slate",
    colors: {
      accent: "#475569",
      accentLight: "#f1f5f9",
      headerBg: "#ffffff",
      headerText: "#0f172a",
      sidebarBg: "#f8fafc",
      sidebarText: "#334155",
      bodyText: "#1e293b",
      mutedText: "#94a3b8",
      border: "#e2e8f0",
    },
    font: "sans",
    headingStyle: "minimal",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "text",
    experienceStyle: "compact",
    sectionDivider: "none",
  },
  // ─── 10. Copper — Warm earth sophistication ───
  {
    id: "copper",
    name: "Copper",
    colors: {
      accent: "#92400e",
      accentLight: "#fffbeb",
      headerBg: "#92400e",
      headerText: "#ffffff",
      sidebarBg: "#fefcf3",
      sidebarText: "#78350f",
      bodyText: "#1c1917",
      mutedText: "#78716c",
      border: "#e8dcc8",
    },
    font: "serif",
    headingStyle: "uppercase-bar",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "dots",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
  // ─── 11. Ocean — Deep ocean blue ───
  {
    id: "ocean",
    name: "Ocean",
    colors: {
      accent: "#1e40af",
      accentLight: "#eff6ff",
      headerBg: "#1e3a8a",
      headerText: "#ffffff",
      sidebarBg: "#f0f4ff",
      sidebarText: "#1e3a8a",
      bodyText: "#1e293b",
      mutedText: "#6b7280",
      border: "#dbeafe",
    },
    font: "sans",
    headingStyle: "filled",
    density: "compact",
    borderRadius: "4px",
    showIcons: true,
    skillDisplay: "tags",
    experienceStyle: "timeline",
    sectionDivider: "none",
  },
  // ─── 12. Forest — Rich pine green ───
  {
    id: "forest",
    name: "Forest",
    colors: {
      accent: "#166534",
      accentLight: "#f0fdf4",
      headerBg: "#14532d",
      headerText: "#ffffff",
      sidebarBg: "#f0fdf4",
      sidebarText: "#166534",
      bodyText: "#1c1917",
      mutedText: "#6b7280",
      border: "#bbf7d0",
    },
    font: "sans",
    headingStyle: "bordered",
    density: "compact",
    borderRadius: "2px",
    showIcons: false,
    skillDisplay: "bars",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
  // ─── 13. Rose — Soft blush elegance ───
  {
    id: "rose",
    name: "Rose",
    colors: {
      accent: "#9f1239",
      accentLight: "#fff1f2",
      headerBg: "#9f1239",
      headerText: "#ffffff",
      sidebarBg: "#fff5f6",
      sidebarText: "#881337",
      bodyText: "#1f2937",
      mutedText: "#6b7280",
      border: "#fecdd3",
    },
    font: "serif",
    headingStyle: "underline",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "dots",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
  // ─── 14. Indigo — Deep indigo night ───
  {
    id: "indigo",
    name: "Indigo",
    colors: {
      accent: "#4338ca",
      accentLight: "#eef2ff",
      headerBg: "#3730a3",
      headerText: "#ffffff",
      sidebarBg: "#f5f3ff",
      sidebarText: "#3730a3",
      bodyText: "#1e293b",
      mutedText: "#6b7280",
      border: "#c7d2fe",
    },
    font: "sans",
    headingStyle: "pill",
    density: "compact",
    borderRadius: "6px",
    showIcons: true,
    skillDisplay: "tags",
    experienceStyle: "card",
    sectionDivider: "gradient",
  },
  // ─── 15. Sand — Warm desert tones ───
  {
    id: "sand",
    name: "Sand",
    colors: {
      accent: "#a16207",
      accentLight: "#fefce8",
      headerBg: "#ffffff",
      headerText: "#1c1917",
      sidebarBg: "#fefdf5",
      sidebarText: "#854d0e",
      bodyText: "#1c1917",
      mutedText: "#78716c",
      border: "#fde68a",
    },
    font: "serif",
    headingStyle: "minimal",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "text",
    experienceStyle: "compact",
    sectionDivider: "none",
  },
  // ─── 16. Graphite — Ultra-dark sleek ───
  {
    id: "graphite",
    name: "Graphite",
    colors: {
      accent: "#18181b",
      accentLight: "#f4f4f5",
      headerBg: "#09090b",
      headerText: "#fafafa",
      sidebarBg: "#fafafa",
      sidebarText: "#18181b",
      bodyText: "#18181b",
      mutedText: "#71717a",
      border: "#d4d4d8",
    },
    font: "sans",
    headingStyle: "uppercase-bar",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "text",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
  // ─── 17. Plum — Rich purple depth ───
  {
    id: "plum",
    name: "Plum",
    colors: {
      accent: "#7e22ce",
      accentLight: "#faf5ff",
      headerBg: "#6b21a8",
      headerText: "#ffffff",
      sidebarBg: "#faf5ff",
      sidebarText: "#6b21a8",
      bodyText: "#1c1917",
      mutedText: "#6b7280",
      border: "#e9d5ff",
    },
    font: "sans",
    headingStyle: "bordered",
    density: "compact",
    borderRadius: "4px",
    showIcons: true,
    skillDisplay: "bars",
    experienceStyle: "timeline",
    sectionDivider: "none",
  },
  // ─── 18. Steel — Industrial blue-gray ───
  {
    id: "steel",
    name: "Steel",
    colors: {
      accent: "#4b5563",
      accentLight: "#f3f4f6",
      headerBg: "#374151",
      headerText: "#f9fafb",
      sidebarBg: "#f9fafb",
      sidebarText: "#374151",
      bodyText: "#1f2937",
      mutedText: "#9ca3af",
      border: "#d1d5db",
    },
    font: "sans",
    headingStyle: "filled",
    density: "compact",
    borderRadius: "2px",
    showIcons: false,
    skillDisplay: "tags",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
  // ─── 19. Emerald — Bright jewel green ───
  {
    id: "emerald",
    name: "Emerald",
    colors: {
      accent: "#059669",
      accentLight: "#ecfdf5",
      headerBg: "#047857",
      headerText: "#ffffff",
      sidebarBg: "#f0fdf9",
      sidebarText: "#065f46",
      bodyText: "#1f2937",
      mutedText: "#6b7280",
      border: "#a7f3d0",
    },
    font: "sans",
    headingStyle: "pill",
    density: "compact",
    borderRadius: "6px",
    showIcons: true,
    skillDisplay: "bars",
    experienceStyle: "card",
    sectionDivider: "gradient",
  },
  // ─── 20. Midnight — Dark navy authority ───
  {
    id: "midnight",
    name: "Midnight",
    colors: {
      accent: "#1e293b",
      accentLight: "#f1f5f9",
      headerBg: "#0f172a",
      headerText: "#f8fafc",
      sidebarBg: "#f8fafc",
      sidebarText: "#1e293b",
      bodyText: "#0f172a",
      mutedText: "#64748b",
      border: "#cbd5e1",
    },
    font: "serif",
    headingStyle: "underline",
    density: "compact",
    borderRadius: "0px",
    showIcons: false,
    skillDisplay: "dots",
    experienceStyle: "standard",
    sectionDivider: "line",
  },
];

export function getStyle(id: string): DesignStyle {
  return STYLES.find(s => s.id === id) || STYLES[0];
}
